import { ICONS, type IconName } from "@/styles/cj/icons";

export type { IconName };

/**
 * C&J icon — inlines the exact symbol markup from design/cj/icons.svg
 * (icons.ts is generated by scripts/sync-cj-design.sh; never edit it).
 */
export function Icon({
  name,
  size = 18,
  className,
}: {
  name: IconName;
  size?: number;
  className?: string;
}) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={1.6}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      aria-hidden="true"
      focusable="false"
      // eslint-disable-next-line react/no-danger -- generated from our own sprite
      dangerouslySetInnerHTML={{ __html: ICONS[name] }}
    />
  );
}
