// GENERATED by scripts/sync-cj-design.sh from design/cj/icons.svg — do not edit.
// Inner markup is identical to the sprite symbols; Icon.tsx inlines it.
export const ICONS = {
  "locate": "<path d=\"M12 2.5v2.5M12 19v2.5M2.5 12h2.5M19 12h2.5\"/> <circle cx=\"12\" cy=\"12\" r=\"5.5\"/> <circle cx=\"12\" cy=\"12\" r=\"1\"/>",
  "elevation": "<path d=\"M3.5 18l5-8 3.5 5 3-4 5 7\"/> <path d=\"M3.5 20.5h17\"/>",
  "layers": "<path d=\"M12 3.5 20.5 8 12 12.5 3.5 8z\"/> <path d=\"M3.5 12 12 16.5 20.5 12\"/> <path d=\"M3.5 16 12 20.5 20.5 16\"/>",
  "filter": "<path d=\"M4 5.5h16l-6.2 7.2v5.3l-3.6 2v-7.3L4 5.5z\"/>",
  "search": "<circle cx=\"11\" cy=\"11\" r=\"6.5\"/> <path d=\"M15.6 15.6 20.5 20.5\"/>",
  "well": "<path d=\"M8.5 3.5h7\"/> <path d=\"M12 3.5V15\"/> <path d=\"M8.5 15 12 19.5 15.5 15\"/> <path d=\"M4 21h16\"/>",
  "drill": "<path d=\"M6.5 21 12 4l5.5 17\"/> <path d=\"M9.2 14h5.6\"/> <path d=\"M4 21h16\"/>",
  "report": "<path d=\"M6.5 3.5h7l4 4v13h-11z\"/> <path d=\"M13.5 3.5v4h4\"/> <path d=\"M9.5 12h5M9.5 15.5h5\"/>",
  "external": "<path d=\"M14.5 4H20v5.5\"/> <path d=\"M11 13 20 4\"/> <path d=\"M19.5 14.5V18a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6.5a2 2 0 0 1 2-2h3.5\"/>",
  "share": "<circle cx=\"6\" cy=\"12\" r=\"2.5\"/> <circle cx=\"17.5\" cy=\"6.5\" r=\"2.5\"/> <circle cx=\"17.5\" cy=\"17.5\" r=\"2.5\"/> <path d=\"M8.3 10.8l6.9-3.6M8.3 13.2l6.9 3.6\"/>",
  "close": "<path d=\"M6 6l12 12M18 6 6 18\"/>",
  "chevron-down": "<path d=\"M5 9l7 7 7-7\"/>",
  "chevron-right": "<path d=\"M9 5l7 7-7 7\"/>",
  "refresh": "<path d=\"M20 11a8 8 0 0 0-13.9-4.6L4 8\"/> <path d=\"M4 4v4h4\"/> <path d=\"M4 13a8 8 0 0 0 13.9 4.6L20 16\"/> <path d=\"M20 20v-4h-4\"/>",
  "weather": "<path d=\"M9 3.2v1.7M3.2 9h1.7M4.9 4.9l1.2 1.2M13.1 4.9l-1.2 1.2\"/> <path d=\"M5.2 12.6A3.8 3.8 0 1 1 12.7 9.9\"/> <path d=\"M12 20.5h6.5a3.2 3.2 0 0 0 .5-6.4 4.6 4.6 0 0 0-8.8-1.3A3 3 0 0 0 11 18.4\"/>",
  "radar": "<path d=\"M12 4a8 8 0 0 1 8 8\"/> <path d=\"M12 8a4 4 0 0 1 4 4\"/> <path d=\"M12 12l6.8-6.8\"/> <circle cx=\"12\" cy=\"12\" r=\"1\"/> <path d=\"M4 12a8 8 0 0 0 14.6 4.4\" opacity=\"0.45\"/> <path d=\"M8 12a4 4 0 0 0 6.9 2.7\" opacity=\"0.45\"/>",
  "map-pin": "<path d=\"M12 21s-6.5-5.4-6.5-10.5a6.5 6.5 0 0 1 13 0C18.5 15.6 12 21 12 21z\"/> <circle cx=\"12\" cy=\"10.5\" r=\"2.5\"/>",
  "info": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/> <path d=\"M12 11v5.5\"/> <path d=\"M12 7.6v.3\"/>",
  "alert": "<path d=\"M12 4 21 19.5H3z\"/> <path d=\"M12 10v4.5\"/> <path d=\"M12 16.9v.3\"/>",
  "check": "<path d=\"M4.5 12.5l5 5L19.5 7\"/>",
  "sun": "<circle cx=\"12\" cy=\"12\" r=\"4\"/> <path d=\"M12 2.5v2M12 19.5v2M2.5 12h2M19.5 12h2M5.3 5.3l1.4 1.4M17.3 17.3l1.4 1.4M5.3 18.7l1.4-1.4M17.3 6.7l1.4-1.4\"/>",
  "moon": "<path d=\"M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5z\"/>",
  "arrow-right": "<path d=\"M4 12h15\"/> <path d=\"M13.5 5.5 20 12l-6.5 6.5\"/>",
  "menu": "<path d=\"M4 7h16M4 12h16M4 17h16\"/>",
} as const;
export type IconName = keyof typeof ICONS;
export const ICON_NAMES = ["locate", "elevation", "layers", "filter", "search", "well", "drill", "report", "external", "share", "close", "chevron-down", "chevron-right", "refresh", "weather", "radar", "map-pin", "info", "alert", "check", "sun", "moon", "arrow-right", "menu"] as const;
