#!/usr/bin/env bash
# sync-cj-design.sh — copy the canonical C&J design system (design/cj/) into the
# places that consume it, and emit the TypeScript icon module so Icon.tsx and
# icons.svg can never drift apart.
#
#   design/cj/*.css + fonts/ + icons.svg   → apps/hub/src/styles/cj/
#                                          (+ icons.ts generated there)
#   design/cj/* (everything, incl. js)     → apps/hub/public/well-viewer/cj/
#
# Usage:
#   scripts/sync-cj-design.sh           write the copies
#   scripts/sync-cj-design.sh --check   verify copies match the source; exit 1 on drift

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/design/cj"
HUB_SRC="$ROOT/apps/hub/src/styles/cj"
VIEWER="$ROOT/apps/hub/public/well-viewer/cj"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

CSS_FILES=(tokens.css base.css components.css motion.css loader.css fonts.css)
JS_FILES=(theme-init.js theme-toggle.js)
FAIL=0

note() { [ "$CHECK" = 1 ] || printf '  %s\n' "$1"; }
drift() { printf 'DRIFT %s\n' "$1" >&2; FAIL=1; }

# copy <src> <dst>: write, or diff in --check mode
copy() {
  local src="$1" dst="$2"
  if [ "$CHECK" = 1 ]; then
    if [ ! -f "$dst" ] || ! cmp -s "$src" "$dst"; then drift "${dst#$ROOT/}"; fi
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    note "write ${dst#$ROOT/}"
  fi
}

# emit_icons_ts <outfile>: parse icons.svg symbols into a TS module
emit_icons_ts() {
  local out="$1"
  node - "$SRC/icons.svg" "$out" <<'NODE'
const fs = require("fs");
const [svgPath, outPath] = process.argv.slice(2);
const svg = fs.readFileSync(svgPath, "utf8");
const re = /<symbol\s+id="i-([\w-]+)"[^>]*>([\s\S]*?)<\/symbol>/g;
const icons = {};
let m;
while ((m = re.exec(svg))) {
  icons[m[1]] = m[2].trim().replace(/\s*\n\s*/g, " ").replace(/"/g, '\\"');
}
const names = Object.keys(icons);
const body = names.map((n) => `  ${JSON.stringify(n)}: "${icons[n]}",`).join("\n");
const ts = `// GENERATED by scripts/sync-cj-design.sh from design/cj/icons.svg — do not edit.
// Inner markup is identical to the sprite symbols; Icon.tsx inlines it.
export const ICONS = {
${body}
} as const;
export type IconName = keyof typeof ICONS;
export const ICON_NAMES = [${names.map((n) => JSON.stringify(n)).join(", ")}] as const;
`;
fs.mkdirSync(require("path").dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, ts);
NODE
}

if [ ! -d "$SRC" ]; then
  echo "missing design source: $SRC" >&2
  exit 1
fi

# --- hub source copy (css + sprite + fonts; js is for static surfaces only) ---
for f in "${CSS_FILES[@]}"; do copy "$SRC/$f" "$HUB_SRC/$f"; done
copy "$SRC/icons.svg" "$HUB_SRC/icons.svg"
for f in "$SRC"/fonts/*; do copy "$f" "$HUB_SRC/fonts/$(basename "$f")"; done

# --- generated TypeScript icon module ---
if [ "$CHECK" = 1 ]; then
  tmp="$(mktemp -t cj-icons.XXXXXX.ts)"
  emit_icons_ts "$tmp"
  if ! cmp -s "$tmp" "$HUB_SRC/icons.ts"; then drift "apps/hub/src/styles/cj/icons.ts"; fi
  rm -f "$tmp"
else
  emit_icons_ts "$HUB_SRC/icons.ts"
  note "write apps/hub/src/styles/cj/icons.ts (generated)"
fi

# --- viewer public copy (everything + viewer-only chrome sheet) ---
for f in "${CSS_FILES[@]}" "${JS_FILES[@]}" icons.svg viewer.css; do copy "$SRC/$f" "$VIEWER/$f"; done
for f in "$SRC"/fonts/*; do copy "$f" "$VIEWER/fonts/$(basename "$f")"; done

if [ "$CHECK" = 1 ]; then
  if [ "$FAIL" = 0 ]; then echo "sync-cj-design: OK — all copies in sync"; else exit 1; fi
else
  echo "sync-cj-design: done"
fi
